#!/usr/bin/env npx tsx
// ============================================================
// Generate LQIP (Low Quality Image Placeholders) blur hashes
// for all game assets. Each placeholder is a tiny 10-pixel-wide
// JPEG encoded as a base64 data URL (~200-400 bytes each).
//
// Usage: npx tsx scripts/generate-blur-hashes.ts
// Output: game/data/scenarios/car-dealership/blur-hashes.ts
// ============================================================

import { readdir } from 'fs/promises';
import { writeFile } from 'fs/promises';
import { join, basename, extname } from 'path';

// sharp is bundled with Next.js
import sharp from 'sharp';

const ASSETS_ROOT = join(
  process.cwd(),
  'public/assets/scenarios/car-dealership',
);
const OUTPUT_FILE = join(
  process.cwd(),
  'game/data/scenarios/car-dealership/blur-hashes.ts',
);

async function generateBlurDataURL(filePath: string): Promise<string> {
  const buffer = await sharp(filePath)
    .resize(10, 6, { fit: 'cover' })
    .jpeg({ quality: 20 })
    .toBuffer();

  return `data:image/jpeg;base64,${buffer.toString('base64')}`;
}

async function processDirectory(
  dir: string,
  prefix: string,
): Promise<Record<string, string>> {
  const results: Record<string, string> = {};

  let files: string[];
  try {
    files = await readdir(dir);
  } catch {
    console.warn(`Directory not found: ${dir}`);
    return results;
  }

  for (const file of files.sort()) {
    const ext = extname(file).toLowerCase();
    if (!['.jpg', '.jpeg', '.webp', '.png'].includes(ext)) continue;
    if (file.endsWith('.bak')) continue;

    const key = `${prefix}/${basename(file, ext)}`;
    const filePath = join(dir, file);

    try {
      results[key] = await generateBlurDataURL(filePath);
      console.log(`  ✓ ${key}`);
    } catch (err) {
      console.warn(`  ✗ ${key}: ${err}`);
    }
  }

  return results;
}

async function main() {
  console.log('Generating blur hashes...\n');

  const backgrounds = await processDirectory(
    join(ASSETS_ROOT, 'backgrounds'),
    'backgrounds',
  );
  const characters = await processDirectory(
    join(ASSETS_ROOT, 'characters'),
    'characters',
  );

  const all = { ...backgrounds, ...characters };
  const count = Object.keys(all).length;

  // Generate TypeScript output
  const lines = [
    '// Auto-generated by scripts/generate-blur-hashes.ts',
    '// Do not edit manually. Re-run: npx tsx scripts/generate-blur-hashes.ts',
    '',
    'export const BLUR_HASHES: Record<string, string> = {',
  ];

  for (const [key, value] of Object.entries(all)) {
    lines.push(`  '${key}': '${value}',`);
  }

  lines.push('};');
  lines.push('');
  lines.push('/** Look up blur placeholder for a background ID (e.g. "bg_showroom"). */');
  lines.push('export function getBackgroundBlur(bgId: string): string | undefined {');
  lines.push("  return BLUR_HASHES[`backgrounds/${bgId}`];");
  lines.push('}');
  lines.push('');
  lines.push('/** Look up blur placeholder for a character sprite path. */');
  lines.push('export function getCharacterBlur(assetPath: string): string | undefined {');
  lines.push('  // assetPath: /assets/scenarios/car-dealership/characters/chr_rustam_friendly.webp');
  lines.push("  const match = assetPath.match(/characters\\/(.+?)\\.[^.]+$/);");
  lines.push('  if (!match) return undefined;');
  lines.push("  return BLUR_HASHES[`characters/${match[1]}`];");
  lines.push('}');
  lines.push('');

  await writeFile(OUTPUT_FILE, lines.join('\n'), 'utf-8');

  console.log(`\n✅ Generated ${count} blur hashes → ${OUTPUT_FILE}`);
}

main().catch((err) => {
  console.error('Fatal:', err);
  process.exit(1);
});
